### ISSUE TITLE
关于按F5开启调试的一个提议

### ISSUE THREAD

**Issue by littlewater** [xmake-io/xmake-vscode#50]
主要是大部分从win平台过来的都习惯了F5，个人觉得最好能够把F5自动开启xmake run -d这个效果，类似nodejs的npm start。

然后我去看了一下关于launch.json的配置以及说明，感觉应该是可以对type这个字段下手，
我是参考了[这里](https://www.jianshu.com/p/d3c6e25ae815)的，他里面type就是用了node，我感觉应该跟xmake调试启动接口类似，但是我接下来不是太明白这个地方type到底能不能自定义修改，可能需要跟vscode的插件实现有关系了吧？

不知道这个思路是不是已经有考虑过？我回头也会继续看看怎么搞。

**Comment by waruqi** [comment]
我刚已经说了，xmake原本就会通过底下的按钮生成launch.json带起调试器，只是没对接任何快捷键而已。。

https://github.com/xmake-io/xmake-vscode/issues/33#issuecomment-703452350

**Comment by littlewater** [comment]
这个我知道能启动，纯键盘我也可以运行，只是觉得按CTRL+SHIFT+P，然后选xmake:debug稍微慢一点，F5太习惯了。
xmake生成的launch.json有没有可能产生到.vscode目录下，我看了一下现在还没有，我下午实验了下launch.json，看了点其他的type的类型，像node，还有extenionHost，也不知道怎么添加自定义的调用的，再研究下去感觉走的太远了，姑且就丢在这便当作一个request，也不是很着急，如果能完善最好吧。

**Comment by littlewater** [comment]
之前我记得#33也有人提过，然后我看到你代码里面的一部分实现，就是内部lua产生动态的launcher，后面肯定都没问题的，纯粹只是使用习惯的事情了。

**Comment by waruqi** [comment]
> 这个我知道能启动，纯键盘我也可以运行，只是觉得按CTRL+SHIFT+P，然后选xmake:debug稍微慢一点，F5太习惯了。

就首次需要切debug mode编译而已，即使f5 首次还是要切debug编译的。。

之后的调试运行，只需要点一些下面你的调试按钮就起来了，也不需要 按CTRL+SHIFT+P ，我感觉比按f5还快，就鼠标点下就好了。。

**Comment by jprochazk** [comment]
I'd also like this feature, because I don't use the mouse much when writing code, and being able to click the keyboard button to start debugging my program would be nice.

@littlewater It is not possible to bind `XMake: Debug` to `F5`, but it is possible to use `F6` instead.

Go into `File > Preferences > Keyboard Shortcuts`, write `xmake` into the search bar, find `XMake: Debug`, right click it and click `Change Keybinding`, then click `F6` and `Enter`. Right click it again and click `Change When Expression`. Write `editorLangId == 'cpp' && debugState != 'running'` into the field, and press `Enter`. This will ensure that F6 will only trigger `XMake: Build` if you are not already in a debugging session.

**Comment by HeBomou** [comment]
感觉还是集成到.vscode/launch.json和tasks.json好一点？

我看隔壁也开始做这个事情了
microsoft/vscode-cmake-tools#1268

**Comment by HeBomou** [comment]
倒也不是说隔壁就很牛逼，只是希望能更好的集成到vscode上

**Comment by waruqi** [comment]
> 感觉还是集成到.vscode/launch.json和tasks.json好一点？
> 
> 我看隔壁也开始做这个事情了
> [microsoft/vscode-cmake-tools#1268](https://github.com/microsoft/vscode-cmake-tools/pull/1268)

主要是我现在暂时没时间研究这块，只能先自己绑定下 凑活着用吧，或者可以帮忙提个pr过来。

**Comment by HeBomou** [comment]
噢噢，确实也是😂😂

**Comment by wangzhankun** [comment]
希望能够增加launch.json和tasks.json，我这边在远程连接的时候总是出现xmake的插件图标无法显示的问题，就很难受。

**Comment by waruqi** [comment]
> launch.json和tasks.json

图标问题，跟增加 launch.json和tasks.json 有什么关系，跟这个issue 也没啥关系，请新开 issue 详细描述问题和复现步骤。

**Comment by wangzhankun** [comment]
> > launch.json和tasks.json
> 
> 图标问题，跟增加 launch.json和tasks.json 有什么关系，跟这个issue 也没啥关系，请新开 issue 详细描述问题和复现步骤。

因为想着加了之后就可以按F5进行debug了，有没有图标也不影响了。同时也方便传参数。

**Comment by waruqi** [comment]
> > > launch.json和tasks.json
> > 
> > 
> > 图标问题，跟增加 launch.json和tasks.json 有什么关系，跟这个issue 也没啥关系，请新开 issue 详细描述问题和复现步骤。
> 
> 因为想着加了之后就可以按F5进行debug了，有没有图标也不影响了。同时也方便传参数。

上面有人提供方案，自己绑到 f6上调，而且按下面的调试按钮 也没麻烦多少

现在也可以传参，暂时没时间搞

**Comment by waruqi** [comment]
可以了，https://github.com/xmake-io/xmake-vscode/pull/99
